name: Run Mergeable

on:  # see subscriptions at https://mergeable.readthedocs.io/en/latest/deployment.html#
  pull_request:
  pull_request_review:
  pull_request_review_comment:
  issues:

jobs:
  mergeable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: webhook-star-bug
      #    repository: mergeability/mergeable
      #    ref: v2.12.1
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 16
      - run: npm ci
      - run: npm i @probot/adapter-github-actions
      #- run: npm run build
      - run: |
          echo 'const { run } = require("@probot/adapter-github-actions"); const app = require("./index"); run(app);' | node
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
